//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "doubles")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub player_id_win1: i32,
    pub player_id_win2: i32,
    pub player_id_loss1: i32,
    pub player_id_loss2: i32,
    pub old_elo_win1: i32,
    pub old_elo_win2: i32,
    pub old_elo_lose1: i32,
    pub old_elo_lose2: i32,
    pub time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::players::Entity",
        from = "Column::PlayerIdLoss1",
        to = "super::players::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Players4,
    #[sea_orm(
        belongs_to = "super::players::Entity",
        from = "Column::PlayerIdLoss2",
        to = "super::players::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Players3,
    #[sea_orm(
        belongs_to = "super::players::Entity",
        from = "Column::PlayerIdWin1",
        to = "super::players::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Players2,
    #[sea_orm(
        belongs_to = "super::players::Entity",
        from = "Column::PlayerIdWin2",
        to = "super::players::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Players1,
}

impl ActiveModelBehavior for ActiveModel {}
