//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "singles")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub player_id_win: i32,
    pub player_id_loss: i32,
    pub old_elo_win: i32,
    pub old_elo_lose: i32,
    pub time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::players::Entity",
        from = "Column::PlayerIdLoss",
        to = "super::players::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Players2,
    #[sea_orm(
        belongs_to = "super::players::Entity",
        from = "Column::PlayerIdWin",
        to = "super::players::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Players1,
}

impl ActiveModelBehavior for ActiveModel {}
